import type { Linha } from './index';

/**
 * A landing page institucional. Colunas: [PT, EN, ES, FR, DE, IT].
 *
 * Os títulos com `**negrito**` levam os marcadores nas TRÊS partes de cada
 * língua: o negrito cai onde a ordem de palavras dela o pede (ver `Rico` em
 * SiteLanding.tsx). Aspas DUPLAS em tudo (apóstrofos do francês/italiano).
 *
 * Tom: direto e caloroso, "você" formal em PT/ES/FR/DE/IT e "you" em EN —
 * como o português de origem, que trata o cliente por "a sua equipa".
 */
export const LANDING: Linha[] = [
  // ------------------------------------------------------- navegação ----
  ["Equipamentos", "Teamwear", "Equipaciones", "Équipements", "Ausrüstung", "Divise"],
  ["Modalidades", "Sports", "Modalidades", "Disciplines", "Sportarten", "Discipline"],
  ["Como Funciona", "How It Works", "Cómo funciona", "Comment ça marche", "So funktioniert's", "Come funziona"],
  ["Entrar no simulador", "Enter the simulator", "Entrar en el simulador", "Accéder au simulateur", "Zum Simulator", "Entra nel simulatore"],

  // ------------------------------------------------------------ hero ----
  ["Equipamentos desportivos personalizados para clubes, equipas e atletas", "Custom sports kits for clubs, teams and athletes", "Equipaciones deportivas personalizadas para clubes, equipos y atletas", "Équipements sportifs personnalisés pour clubs, équipes et athlètes", "Individuelle Sportausrüstung für Vereine, Teams und Athleten", "Divise sportive personalizzate per club, squadre e atleti"],
  ["Produção própria", "In-house production", "Producción propia", "Production maison", "Eigene Produktion", "Produzione propria"],
  ["Personalização total", "Full customization", "Personalización total", "Personnalisation totale", "Vollständige Personalisierung", "Personalizzazione totale"],
  ["Tecidos técnicos de elevada qualidade", "High-quality technical fabrics", "Tejidos técnicos de alta calidad", "Tissus techniques de haute qualité", "Hochwertige technische Stoffe", "Tessuti tecnici di alta qualità"],
  ["Soluções para todas as modalidades", "Solutions for every sport", "Soluciones para todas las modalidades", "Des solutions pour toutes les disciplines", "Lösungen für alle Sportarten", "Soluzioni per tutte le discipline"],
  ["unidades produzidas", "units produced", "unidades producidas", "unités produites", "produzierte Einheiten", "unità prodotte"],
  ["Concebemos equipamentos técnicos que combinam desempenho, conforto e identidade. Da primeira ideia à produção final, acompanhamos todo o processo para criar soluções totalmente personalizadas para a sua equipa.", "We design technical kits that combine performance, comfort and identity. From the first idea to final production, we guide the whole process to create fully customized solutions for your team.", "Diseñamos equipaciones técnicas que combinan rendimiento, comodidad e identidad. Desde la primera idea hasta la producción final, acompañamos todo el proceso para crear soluciones totalmente personalizadas para su equipo.", "Nous concevons des équipements techniques alliant performance, confort et identité. De la première idée à la production finale, nous accompagnons tout le processus pour créer des solutions entièrement personnalisées pour votre équipe.", "Wir entwickeln technische Ausrüstung, die Leistung, Komfort und Identität vereint. Von der ersten Idee bis zur Fertigung begleiten wir den gesamten Prozess und schaffen vollständig individuelle Lösungen für Ihr Team.", "Progettiamo divise tecniche che uniscono prestazioni, comfort e identità. Dalla prima idea alla produzione finale, seguiamo l'intero processo per creare soluzioni totalmente personalizzate per la tua squadra."],

  // ------------------------------------------------ processo/qualidade ----
  ["Todo o processo. **Sob o mesmo compromisso** de qualidade.", "The whole process. **Under the same commitment** to quality.", "Todo el proceso. **Bajo el mismo compromiso** de calidad.", "Tout le processus. **Avec le même engagement** de qualité.", "Der gesamte Prozess. **Mit demselben Anspruch** an Qualität.", "Tutto il processo. **Con lo stesso impegno** di qualità."],
  ["Na KYPZL controlamos todas as etapas da produção, desde o design até à confeção. Este modelo permite-nos garantir maior controlo, qualidade consistente e um acompanhamento mais próximo em cada projeto.", "At KYPZL we control every stage of production, from design to sewing. This model lets us guarantee greater control, consistent quality and closer follow-up on every project.", "En KYPZL controlamos todas las etapas de la producción, desde el diseño hasta la confección. Este modelo nos permite garantizar mayor control, calidad constante y un seguimiento más cercano en cada proyecto.", "Chez KYPZL, nous maîtrisons toutes les étapes de la production, du design à la confection. Ce modèle nous permet de garantir un meilleur contrôle, une qualité constante et un suivi plus proche pour chaque projet.", "Bei KYPZL kontrollieren wir alle Produktionsschritte, vom Design bis zur Konfektion. So garantieren wir mehr Kontrolle, gleichbleibende Qualität und eine engere Betreuung bei jedem Projekt.", "In KYPZL controlliamo tutte le fasi della produzione, dal design alla confezione. Questo modello ci permette di garantire maggiore controllo, qualità costante e un'assistenza più vicina in ogni progetto."],
  ["Conforto & Performance", "Comfort & Performance", "Comodidad y rendimiento", "Confort et performance", "Komfort & Leistung", "Comfort e prestazioni"],
  ["Tecidos técnicos de alta qualidade", "High-quality technical fabrics", "Tejidos técnicos de alta calidad", "Tissus techniques de haute qualité", "Hochwertige technische Stoffe", "Tessuti tecnici di alta qualità"],
  ["Materiais respiráveis, leves e resistentes, desenvolvidos para proporcionar o máximo desempenho em competição e treino.", "Breathable, lightweight and durable materials, developed to deliver maximum performance in competition and training.", "Materiales transpirables, ligeros y resistentes, desarrollados para ofrecer el máximo rendimiento en competición y entrenamiento.", "Des matières respirantes, légères et résistantes, conçues pour offrir des performances maximales en compétition comme à l'entraînement.", "Atmungsaktive, leichte und widerstandsfähige Materialien für maximale Leistung in Wettkampf und Training.", "Materiali traspiranti, leggeri e resistenti, sviluppati per offrire il massimo delle prestazioni in gara e in allenamento."],
  ["Design Exclusivo", "Exclusive Design", "Diseño exclusivo", "Design exclusif", "Exklusives Design", "Design esclusivo"],
  ["Identidade visual da sua equipe", "Your team's visual identity", "La identidad visual de su equipo", "L'identité visuelle de votre équipe", "Die visuelle Identität Ihres Teams", "L'identità visiva della tua squadra"],
  ["Cada equipamento é criado do zero, com sublimação digital, para refletir a identidade única do seu clube ou equipa.", "Every kit is created from scratch with digital sublimation to reflect the unique identity of your club or team.", "Cada equipación se crea desde cero, con sublimación digital, para reflejar la identidad única de su club o equipo.", "Chaque équipement est créé de zéro, en sublimation numérique, pour refléter l'identité unique de votre club ou équipe.", "Jede Ausrüstung wird von Grund auf mit digitaler Sublimation gefertigt und spiegelt die einzigartige Identität Ihres Vereins oder Teams wider.", "Ogni divisa viene creata da zero, con sublimazione digitale, per riflettere l'identità unica del tuo club o della tua squadra."],

  // ------------------------------------------------------ como funciona ---
  ["Desenvolvemos equipamentos que **representam a identidade** da sua equipa.", "We develop kits that **represent the identity** of your team.", "Desarrollamos equipaciones que **representan la identidad** de su equipo.", "Nous développons des équipements qui **représentent l'identité** de votre équipe.", "Wir entwickeln Ausrüstung, die **die Identität Ihres Teams** verkörpert.", "Sviluppiamo divise che **rappresentano l'identità** della tua squadra."],
  ["Cada projeto é único. Trabalhamos consigo para criar equipamentos totalmente personalizados através de tecnologia de sublimação, materiais técnicos e acabamentos de elevada qualidade.", "Every project is unique. We work with you to create fully customized kits using sublimation technology, technical materials and high-quality finishes.", "Cada proyecto es único. Trabajamos con usted para crear equipaciones totalmente personalizadas mediante tecnología de sublimación, materiales técnicos y acabados de alta calidad.", "Chaque projet est unique. Nous travaillons avec vous pour créer des équipements entièrement personnalisés grâce à la sublimation, à des matériaux techniques et à des finitions de haute qualité.", "Jedes Projekt ist einzigartig. Gemeinsam mit Ihnen entwickeln wir vollständig individuelle Ausrüstung mit Sublimationstechnik, technischen Materialien und hochwertiger Verarbeitung.", "Ogni progetto è unico. Lavoriamo con te per creare divise totalmente personalizzate grazie alla tecnologia di sublimazione, a materiali tecnici e a finiture di alta qualità."],
  ["Passo", "Step", "Paso", "Étape", "Schritt", "Passo"],
  ["Partilhe a sua ideia conosco.", "Share your idea with us.", "Comparta su idea con nosotros.", "Partagez votre idée avec nous.", "Teilen Sie uns Ihre Idee mit.", "Condividi la tua idea con noi."],
  ["Conta-nos sobre a sua equipa, cores, modalidade e tudo o que imagina.", "Tell us about your team, colors, sport and everything you have in mind.", "Cuéntenos sobre su equipo, los colores, la modalidad y todo lo que imagina.", "Parlez-nous de votre équipe, des couleurs, de la discipline et de tout ce que vous imaginez.", "Erzählen Sie uns von Ihrem Team, den Farben, der Sportart und allem, was Sie sich vorstellen.", "Raccontaci della tua squadra, dei colori, della disciplina e di tutto ciò che immagini."],
  ["Desenvolvemos o design.", "We develop the design.", "Desarrollamos el diseño.", "Nous développons le design.", "Wir entwickeln das Design.", "Sviluppiamo il design."],
  ["A nossa equipa cria uma proposta visual exclusiva para aprovação.", "Our team creates an exclusive visual proposal for your approval.", "Nuestro equipo crea una propuesta visual exclusiva para su aprobación.", "Notre équipe crée une proposition visuelle exclusive pour votre validation.", "Unser Team erstellt einen exklusiven visuellen Entwurf zur Freigabe.", "Il nostro team crea una proposta visiva esclusiva da approvare."],
  ["Produzimos através de sublimação.", "We produce through sublimation.", "Producimos mediante sublimación.", "Nous produisons par sublimation.", "Wir produzieren im Sublimationsverfahren.", "Produciamo tramite sublimazione."],
  ["Imprimimos o design em tecido técnico com cores vibrantes e duradouras.", "We print the design on technical fabric with vibrant, long-lasting colors.", "Imprimimos el diseño sobre tejido técnico con colores vibrantes y duraderos.", "Nous imprimons le design sur tissu technique avec des couleurs vives et durables.", "Wir drucken das Design auf technischen Stoff — in leuchtenden, langlebigen Farben.", "Stampiamo il design su tessuto tecnico con colori vivaci e duraturi."],
  ["Realizamos o corte e a confeção.", "We handle the cutting and sewing.", "Realizamos el corte y la confección.", "Nous réalisons la coupe et la confection.", "Wir übernehmen Zuschnitt und Konfektion.", "Realizziamo il taglio e la confezione."],
  ["Cada peça é cortada e cosida com precisão e acabamentos impecáveis.", "Every piece is cut and sewn with precision and flawless finishing.", "Cada prenda se corta y se cose con precisión y acabados impecables.", "Chaque pièce est coupée et cousue avec précision et des finitions impeccables.", "Jedes Teil wird präzise zugeschnitten und genäht — mit einwandfreier Verarbeitung.", "Ogni capo viene tagliato e cucito con precisione e finiture impeccabili."],
  ["Efetuamos o controlo de qualidade.", "We carry out quality control.", "Realizamos el control de calidad.", "Nous effectuons le contrôle qualité.", "Wir führen die Qualitätskontrolle durch.", "Eseguiamo il controllo qualità."],
  ["Inspeção rigorosa antes de enviar o equipamento pronto para campo.", "A rigorous inspection before sending the kit out, ready for the pitch.", "Inspección rigurosa antes de enviar la equipación lista para el campo.", "Une inspection rigoureuse avant l'envoi de l'équipement, prêt pour le terrain.", "Strenge Prüfung, bevor die Ausrüstung einsatzbereit für den Platz versendet wird.", "Ispezione rigorosa prima di spedire la divisa, pronta per il campo."],
  ["Receba o seu equipamento.", "Receive your kit.", "Reciba su equipación.", "Recevez votre équipement.", "Erhalten Sie Ihre Ausrüstung.", "Ricevi la tua divisa."],
  ["Entregamos nos prazos acordados, prontos a entrar em campo.", "We deliver on the agreed deadlines, ready to step onto the pitch.", "Entregamos en los plazos acordados, listos para saltar al campo.", "Nous livrons dans les délais convenus, prêts à entrer sur le terrain.", "Wir liefern zu den vereinbarten Terminen — bereit für den Einsatz auf dem Platz.", "Consegniamo nei tempi concordati, pronti a scendere in campo."],

  // --------------------------------------------------------- modalidades --
  ["Soluções para **qualquer modalidade** desportiva", "Solutions for **any sport**", "Soluciones para **cualquier modalidad** deportiva", "Des solutions pour **toute discipline** sportive", "Lösungen für **jede Sportart**", "Soluzioni per **qualsiasi disciplina** sportiva"],
  ["Produzimos equipamentos personalizados adaptados às exigências de cada modalidade.", "We produce custom kits tailored to the demands of each sport.", "Producimos equipaciones personalizadas adaptadas a las exigencias de cada modalidad.", "Nous produisons des équipements personnalisés adaptés aux exigences de chaque discipline.", "Wir fertigen individuelle Ausrüstung, abgestimmt auf die Anforderungen jeder Sportart.", "Produciamo divise personalizzate adatte alle esigenze di ogni disciplina."],
  ["Futsal", "Futsal", "Fútbol sala", "Futsal", "Futsal", "Calcio a 5"],
  ["Andebol", "Handball", "Balonmano", "Handball", "Handball", "Pallamano"],
  ["Atletismo", "Athletics", "Atletismo", "Athlétisme", "Leichtathletik", "Atletica"],
  ["Hóquei em Patins", "Roller hockey", "Hockey sobre patines", "Rink hockey", "Rollhockey", "Hockey su pista"],
  ["Outras Modalidades", "Other Sports", "Otras modalidades", "Autres disciplines", "Weitere Sportarten", "Altre discipline"],

  // ----------------------------------------------------- premium/champion --
  ["Concebidos para competir ao **mais alto nível**.", "Built to compete at the **highest level**.", "Concebidas para competir al **más alto nivel**.", "Conçus pour concourir au **plus haut niveau**.", "Entwickelt für den Wettkampf auf **höchstem Niveau**.", "Pensate per competere ai **massimi livelli**."],
  ["Equipamentos desenvolvidos para proporcionar conforto, resistência e total liberdade de movimentos.", "Kits designed to deliver comfort, durability and complete freedom of movement.", "Equipaciones desarrolladas para ofrecer comodidad, resistencia y total libertad de movimientos.", "Des équipements conçus pour offrir confort, résistance et totale liberté de mouvement.", "Ausrüstung, die Komfort, Strapazierfähigkeit und volle Bewegungsfreiheit bietet.", "Divise sviluppate per offrire comfort, resistenza e totale libertà di movimento."],
  ["Linha", "Line", "Línea", "Gamme", "Linie", "Linea"],
  ["Desempenho de Elite", "Elite Performance", "Rendimiento de élite", "Performance d'élite", "Spitzenleistung", "Prestazioni d'élite"],
  ["Camisolas", "Jerseys", "Camisetas", "Maillots", "Trikots", "Maglie"],
  ["Calções", "Shorts", "Pantalones cortos", "Shorts", "Shorts", "Pantaloncini"],
  ["Equipamentos de Guarda-Redes", "Goalkeeper Kits", "Equipaciones de portero", "Équipements de gardien", "Torwartausrüstung", "Divise da portiere"],
  ["Meias", "Socks", "Medias", "Chaussettes", "Socken", "Calze"],

  // ------------------------------------------------------------ treino ----
  ["**Preparados** para acompanhar cada treino.", "**Ready** for every training session.", "**Preparados** para acompañar cada entrenamiento.", "**Prêts** à vous accompagner à chaque entraînement.", "**Bereit** für jedes Training.", "**Pronti** per ogni allenamento."],
  ["A coleção de treino KYPZL combina conforto, respirabilidade e durabilidade para responder às exigências do dia a dia.", "The KYPZL training collection combines comfort, breathability and durability to meet the demands of everyday training.", "La colección de entrenamiento KYPZL combina comodidad, transpirabilidad y durabilidad para responder a las exigencias del día a día.", "La collection d'entraînement KYPZL allie confort, respirabilité et durabilité pour répondre aux exigences du quotidien.", "Die KYPZL-Trainingskollektion vereint Komfort, Atmungsaktivität und Langlebigkeit für die Anforderungen des Alltags.", "La collezione allenamento KYPZL unisce comfort, traspirabilità e durata per rispondere alle esigenze di ogni giorno."],
  ["T-Shirts Técnicas", "Technical T-Shirts", "Camisetas técnicas", "T-shirts techniques", "Funktionsshirts", "T-shirt tecniche"],
  ["Sweats", "Sweatshirts", "Sudaderas", "Sweats", "Sweatshirts", "Felpe"],
  ["Calças", "Pants", "Pantalones", "Pantalons", "Hosen", "Pantaloni"],
  ["Corta-Ventos", "Windbreakers", "Cortavientos", "Coupe-vents", "Windjacken", "Giacche a vento"],
  ["Coletes", "Vests", "Chalecos", "Gilets", "Westen", "Gilet"],
  ["Vestuário Térmico", "Thermal Wear", "Ropa térmica", "Vêtements thermiques", "Thermokleidung", "Abbigliamento termico"],

  // ----------------------------------------------------------- lifestyle --
  ["Lifestyle & Viagem", "Lifestyle & Travel", "Lifestyle y viaje", "Lifestyle et voyage", "Lifestyle & Reise", "Lifestyle e viaggio"],
  ["Uma imagem **profissional dentro e fora** da competição.", "A **professional image on and off** the pitch.", "Una imagen **profesional dentro y fuera** de la competición.", "Une image **professionnelle sur et en dehors** de la compétition.", "Ein **professioneller Auftritt auf und neben** dem Platz.", "Un'immagine **professionale dentro e fuori** dalla competizione."],
  ["Coleção desenvolvida para deslocações, eventos e representação institucional, mantendo o conforto e a identidade visual da equipa.", "A collection designed for travel, events and institutional representation, keeping the team's comfort and visual identity.", "Colección desarrollada para desplazamientos, eventos y representación institucional, manteniendo la comodidad y la identidad visual del equipo.", "Une collection conçue pour les déplacements, les événements et la représentation institutionnelle, tout en préservant le confort et l'identité visuelle de l'équipe.", "Eine Kollektion für Reisen, Veranstaltungen und offizielle Auftritte, die Komfort und visuelle Identität des Teams bewahrt.", "Una collezione pensata per trasferte, eventi e rappresentanza istituzionale, che mantiene il comfort e l'identità visiva della squadra."],
  ["Kits", "Kits", "Kits", "Kits", "Sets", "Kit"],
  ["Casacos", "Coats", "Chaquetas", "Vestes", "Jacken", "Giacconi"],
  ["Blusões", "Bomber jackets", "Cazadoras", "Blousons", "Blousons", "Giubbotti"],
  ["Polos", "Polos", "Polos", "Polos", "Poloshirts", "Polo"],
  ["Bermudas", "Bermuda shorts", "Bermudas", "Bermudas", "Bermudas", "Bermuda"],

  // ---------------------------------------------------------- acessórios --
  ["Tudo o que a sua equipa precisa **num só lugar**.", "Everything your team needs **in one place**.", "Todo lo que su equipo necesita **en un solo lugar**.", "Tout ce dont votre équipe a besoin **au même endroit**.", "Alles, was Ihr Team braucht — **an einem Ort**.", "Tutto ciò di cui la tua squadra ha bisogno **in un unico posto**."],
  ["Complete o equipamento com acessórios desenvolvidos para facilitar o transporte, a organização e a utilização diária.", "Complete the kit with accessories designed to make carrying, organizing and daily use easier.", "Complete la equipación con accesorios pensados para facilitar el transporte, la organización y el uso diario.", "Complétez l'équipement avec des accessoires conçus pour faciliter le transport, l'organisation et l'usage quotidien.", "Ergänzen Sie die Ausrüstung mit Zubehör, das Transport, Organisation und den täglichen Gebrauch erleichtert.", "Completa la divisa con accessori pensati per facilitare il trasporto, l'organizzazione e l'uso quotidiano."],
  ["Mochilas", "Backpacks", "Mochilas", "Sacs à dos", "Rucksäcke", "Zaini"],
  ["Compactas e organizadas para o essencial do dia a dia.", "Compact and organized for everyday essentials.", "Compactas y organizadas para lo esencial del día a día.", "Compacts et organisés pour l'essentiel du quotidien.", "Kompakt und gut organisiert für das Wesentliche im Alltag.", "Compatti e organizzati per l'essenziale di ogni giorno."],
  ["Sacos Desportivos", "Sports Bags", "Bolsas deportivas", "Sacs de sport", "Sporttaschen", "Borsoni sportivi"],
  ["Trolleys", "Trolleys", "Trolleys", "Valises à roulettes", "Trolleys", "Trolley"],

  // ------------------------------------------------------- testemunhos ----
  ["A KYPZL superou todas as expectativas. Os equipamentos chegaram no prazo, com qualidade excecional e o design ficou exatamente como queríamos.", "KYPZL exceeded all expectations. The kits arrived on time, with exceptional quality, and the design turned out exactly as we wanted.", "KYPZL superó todas las expectativas. Las equipaciones llegaron a tiempo, con una calidad excepcional, y el diseño quedó exactamente como queríamos.", "KYPZL a dépassé toutes nos attentes. Les équipements sont arrivés à temps, d'une qualité exceptionnelle, et le design est exactement comme nous le voulions.", "KYPZL hat alle Erwartungen übertroffen. Die Ausrüstung kam pünktlich, in außergewöhnlicher Qualität, und das Design wurde genau so, wie wir es wollten.", "KYPZL ha superato ogni aspettativa. Le divise sono arrivate in tempo, con qualità eccezionale, e il design è venuto esattamente come volevamo."],
  ["Diretor Desportivo · SC Porto", "Sporting Director · SC Porto", "Director deportivo · SC Porto", "Directeur sportif · SC Porto", "Sportdirektor · SC Porto", "Direttore sportivo · SC Porto"],
  ["A atenção ao detalhe e o acompanhamento da KYPZL são incomparáveis. Recomendamos sem hesitar a qualquer clube.", "KYPZL's attention to detail and support are unmatched. We recommend them to any club without hesitation.", "La atención al detalle y el acompañamiento de KYPZL son incomparables. Lo recomendamos sin dudar a cualquier club.", "L'attention portée aux détails et l'accompagnement de KYPZL sont incomparables. Nous les recommandons sans hésiter à tout club.", "KYPZLs Liebe zum Detail und die Betreuung sind unvergleichlich. Wir empfehlen sie ohne zu zögern jedem Verein.", "L'attenzione ai dettagli e l'assistenza di KYPZL sono impareggiabili. Lo consigliamo senza esitazione a qualsiasi club."],
  ["Presidente · AD Norte", "President · AD Norte", "Presidenta · AD Norte", "Présidente · AD Norte", "Präsidentin · AD Norte", "Presidente · AD Norte"],
  ["Os nossos atletas adoraram os equipamentos. A qualidade dos tecidos e o conforto fizeram toda a diferença na performance.", "Our athletes loved the kits. The quality of the fabrics and the comfort made all the difference to performance.", "A nuestros atletas les encantaron las equipaciones. La calidad de los tejidos y la comodidad marcaron la diferencia en el rendimiento.", "Nos athlètes ont adoré les équipements. La qualité des tissus et le confort ont fait toute la différence en termes de performance.", "Unsere Athleten waren begeistert. Die Qualität der Stoffe und der Komfort haben für die Leistung den Unterschied gemacht.", "I nostri atleti hanno adorato le divise. La qualità dei tessuti e il comfort hanno fatto la differenza nelle prestazioni."],
  ["Treinador · FC Atlético", "Coach · FC Atlético", "Entrenador · FC Atlético", "Entraîneur · FC Atlético", "Trainer · FC Atlético", "Allenatore · FC Atlético"],
  ["Profissionalismo do início ao fim. Da primeira reunião à entrega, sentimos que a KYPZL vestiu a camisola do nosso clube.", "Professionalism from start to finish. From the first meeting to delivery, we felt KYPZL wore our club's colors.", "Profesionalidad de principio a fin. Desde la primera reunión hasta la entrega, sentimos que KYPZL se puso la camiseta de nuestro club.", "Du professionnalisme du début à la fin. De la première réunion à la livraison, nous avons senti que KYPZL portait les couleurs de notre club.", "Professionalität von Anfang bis Ende. Vom ersten Treffen bis zur Lieferung hatten wir das Gefühl, dass KYPZL unser Vereinstrikot mit Stolz trägt.", "Professionalità dall'inizio alla fine. Dal primo incontro alla consegna, abbiamo sentito che KYPZL ha indossato la maglia del nostro club."],
  ["Coordenadora · Ginásio Clube", "Coordinator · Ginásio Clube", "Coordinadora · Ginásio Clube", "Coordinatrice · Ginásio Clube", "Koordinatorin · Ginásio Clube", "Coordinatrice · Ginásio Clube"],

  // ---------------------------------------------- newsletter e rodapé ----
  ["Siga a KYPZL e acompanhe os nossos projetos mais recentes", "Follow KYPZL and keep up with our latest projects", "Siga a KYPZL y descubra nuestros proyectos más recientes", "Suivez KYPZL et découvrez nos projets les plus récents", "Folgen Sie KYPZL und verfolgen Sie unsere neuesten Projekte", "Segui KYPZL e scopri i nostri progetti più recenti"],
  ["Siga a KYPZL e acompanhe os nossos projetos mais recentes.", "Follow KYPZL and keep up with our latest projects.", "Siga a KYPZL y descubra nuestros proyectos más recientes.", "Suivez KYPZL et découvrez nos projets les plus récents.", "Folgen Sie KYPZL und verfolgen Sie unsere neuesten Projekte.", "Segui KYPZL e scopri i nostri progetti più recenti."],
  ["Seguir no Instagram", "Follow on Instagram", "Seguir en Instagram", "Suivre sur Instagram", "Auf Instagram folgen", "Segui su Instagram"],
  ["Navegação", "Navigation", "Navegación", "Navigation", "Navigation", "Navigazione"],
  ["Equipamentos de Jogo", "Match Kits", "Equipaciones de juego", "Équipements de match", "Spielausrüstung", "Divise da gara"],
  ["Equipamentos de Treino", "Training Kits", "Equipaciones de entrenamiento", "Équipements d'entraînement", "Trainingsausrüstung", "Divise da allenamento"],
  ["Vestuário de Saída", "Travel Wear", "Ropa de viaje", "Tenue de sortie", "Reisebekleidung", "Abbigliamento da viaggio"],
  ["Material e Acessórios", "Gear & Accessories", "Material y accesorios", "Matériel et accessoires", "Material & Zubehör", "Materiale e accessori"],
  ["Morada", "Address", "Dirección", "Adresse", "Adresse", "Indirizzo"],
  ["Horário", "Opening hours", "Horario", "Horaires", "Öffnungszeiten", "Orari"],
  ["Seg - Sex: 09h00 às 18h00", "Mon - Fri: 9:00 am to 6:00 pm", "Lun - Vie: de 09:00 a 18:00", "Lun - Ven : 9h00 à 18h00", "Mo - Fr: 09:00 bis 18:00 Uhr", "Lun - Ven: dalle 9:00 alle 18:00"],
  ["Todos os direitos reservados.", "All rights reserved.", "Todos los derechos reservados.", "Tous droits réservés.", "Alle Rechte vorbehalten.", "Tutti i diritti riservati."],
  ["Feito com sublimação de alta qualidade", "Made with high-quality sublimation", "Hecho con sublimación de alta calidad", "Réalisé en sublimation haute qualité", "Gefertigt mit hochwertiger Sublimation", "Realizzato con sublimazione di alta qualità"],
];
